FROM public.ecr.aws/lambda/python:3.12

RUN dnf install -y gcc postgresql-devel

COPY requirements.txt .
RUN pip install -r requirements.txt --target ${LAMBDA_TASK_ROOT}

COPY lambda_function.py ${LAMBDA_TASK_ROOT}

CMD ["lambda_function.lambda_handler"]